// AUTO-GENERATED BY cxxbridge

#include "vtk_algorithm.h"

using vtkAlgorithm = ::vtkAlgorithm;

extern "C" {
::vtkAlgorithm *cxxbridge1$algorithm_new() noexcept {
  ::vtkAlgorithm *(*algorithm_new$)() = ::algorithm_new;
  return algorithm_new$();
}

void cxxbridge1$algorithm_delete(::vtkAlgorithm &algorithm) noexcept {
  void (*algorithm_delete$)(::vtkAlgorithm &) = ::algorithm_delete;
  algorithm_delete$(algorithm);
}
} // extern "C"
