// AUTO-GENERATED BY cxxbridge

#include "vtk_information.h"

using vtkInformation = ::vtkInformation;

extern "C" {
::vtkInformation *cxxbridge1$vtk_information_new() noexcept {
  ::vtkInformation *(*vtk_information_new$)() = ::vtk_information_new;
  return vtk_information_new$();
}

void cxxbridge1$vtk_information_delete(::vtkInformation &information) noexcept {
  void (*vtk_information_delete$)(::vtkInformation &) = ::vtk_information_delete;
  vtk_information_delete$(information);
}
} // extern "C"
