// AUTO-GENERATED BY cxxbridge

#include "vtk_sphere_source.h"

using vtkSphereSource = ::vtkSphereSource;

extern "C" {
::vtkSphereSource *cxxbridge1$sphere_source_new() noexcept {
  ::vtkSphereSource *(*sphere_source_new$)() = ::sphere_source_new;
  return sphere_source_new$();
}

void cxxbridge1$sphere_source_delete(::vtkSphereSource &ptr) noexcept {
  void (*sphere_source_delete$)(::vtkSphereSource &) = ::sphere_source_delete;
  sphere_source_delete$(ptr);
}
} // extern "C"
