// AUTO-GENERATED BY cxxbridge

#include "vtk_algorithm.h"

using vtkAlgorithm = ::vtkAlgorithm;

extern "C" {
::vtkAlgorithm *cxxbridge1$vtk_algorithm_new() noexcept {
  ::vtkAlgorithm *(*vtk_algorithm_new$)() = ::vtk_algorithm_new;
  return vtk_algorithm_new$();
}

void cxxbridge1$vtk_algorithm_delete(::vtkAlgorithm &algorithm) noexcept {
  void (*vtk_algorithm_delete$)(::vtkAlgorithm &) = ::vtk_algorithm_delete;
  vtk_algorithm_delete$(algorithm);
}
} // extern "C"
