// AUTO-GENERATED BY cxxbridge

#include "vtk_data_object.h"

using vtkDataObject = ::vtkDataObject;

extern "C" {
::vtkDataObject *cxxbridge1$data_object_new() noexcept {
  ::vtkDataObject *(*data_object_new$)() = ::data_object_new;
  return data_object_new$();
}

void cxxbridge1$data_object_delete(::vtkDataObject &data_object) noexcept {
  void (*data_object_delete$)(::vtkDataObject &) = ::data_object_delete;
  data_object_delete$(data_object);
}
} // extern "C"
