// AUTO-GENERATED BY cxxbridge

#include "vtk_poly_data_mapper.h"

using vtkPolyDataMapper = ::vtkPolyDataMapper;

extern "C" {
::vtkPolyDataMapper *cxxbridge1$poly_data_mapper_new() noexcept {
  ::vtkPolyDataMapper *(*poly_data_mapper_new$)() = ::poly_data_mapper_new;
  return poly_data_mapper_new$();
}

void cxxbridge1$poly_data_mapper_delete(::vtkPolyDataMapper *pdm) noexcept {
  void (*poly_data_mapper_delete$)(::vtkPolyDataMapper *) = ::poly_data_mapper_delete;
  poly_data_mapper_delete$(pdm);
}
} // extern "C"
