// AUTO-GENERATED BY cxxbridge

#include "vtk_sphere_source.h"

using vtkSphereSourcePointer = ::vtkSphereSourcePointer;

extern "C" {
::vtkSphereSourcePointer *cxxbridge1$sphere_source_new2() noexcept {
  ::vtkSphereSourcePointer *(*sphere_source_new2$)() = ::sphere_source_new2;
  return sphere_source_new2$();
}

void cxxbridge1$sphere_source_delete2(::vtkSphereSourcePointer const &ptr) noexcept {
  void (*sphere_source_delete2$)(::vtkSphereSourcePointer const &) = ::sphere_source_delete2;
  sphere_source_delete2$(ptr);
}
} // extern "C"
