// AUTO-GENERATED BY cxxbridge

#include "vtk_poly_data.h"

using vtkPolyData = ::vtkPolyData;

extern "C" {
::vtkPolyData *cxxbridge1$poly_data_new() noexcept {
  ::vtkPolyData *(*poly_data_new$)() = ::poly_data_new;
  return poly_data_new$();
}

void cxxbridge1$poly_data_delete(::vtkPolyData &ptr) noexcept {
  void (*poly_data_delete$)(::vtkPolyData &) = ::poly_data_delete;
  poly_data_delete$(ptr);
}
} // extern "C"
