// AUTO-GENERATED BY cxxbridge

#include "vtk_named_colors.h"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmissing-declarations"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__
#endif // __GNUC__

using vtkNamedColors = ::vtkNamedColors;

extern "C" {
::vtkNamedColors *cxxbridge1$190$named_colors_new() noexcept {
  ::vtkNamedColors *(*named_colors_new$)() = ::named_colors_new;
  return named_colors_new$();
}

void cxxbridge1$190$named_colors_delete(::vtkNamedColors &named_colors) noexcept {
  void (*named_colors_delete$)(::vtkNamedColors &) = ::named_colors_delete;
  named_colors_delete$(named_colors);
}
} // extern "C"
