// AUTO-GENERATED BY cxxbridge

#include "vtk_executive.h"

using vtkExecutive = ::vtkExecutive;

extern "C" {
void cxxbridge1$vtk_executive_delete(::vtkExecutive &executive) noexcept {
  void (*vtk_executive_delete$)(::vtkExecutive &) = ::vtk_executive_delete;
  vtk_executive_delete$(executive);
}
} // extern "C"
