import matplotlib.pyplot as plt
import numpy as np

data = [
    ("vtkAcceleratorsVTKmCore", 0),
    ("vtkAcceleratorsVTKmDataModel", 0),
    ("vtkAcceleratorsVTKmFilters", 0),
    ("vtkChartsCore", 526),
    ("vtkCommonArchive", 0),
    ("vtkCommonColor", 0),
    ("vtkCommonComputationalGeometry", 65),
    ("vtkCommonCore", 1096),
    ("vtkCommonDataModel", 1893),
    ("vtkCommonExecutionModel", 645),
    ("vtkCommonMath", 60),
    ("vtkCommonMisc", 0),
    ("vtkCommonPython", 0),
    ("vtkCommonSystem", 8),
    ("vtkCommonTransforms", 90),
    ("vtkDomainsChemistry", 81),
    ("vtkDomainsChemistryOpenGL2", 0),
    ("vtkDomainsParallelChemistry", 0),
    ("vtkFiltersAMR", 0),
    ("vtkFiltersCellGrid", 63),
    ("vtkFiltersCore", 725),
    ("vtkFiltersExtraction", 80),
    ("vtkFiltersFlowPaths", 247),
    ("vtkFiltersGeneral", 244),
    ("vtkFiltersGeneric", 0),
    ("vtkFiltersGeometry", 194),
    ("vtkFiltersGeometryPreview", 0),
    ("vtkFiltersHybrid", 9),
    ("vtkFiltersHyperTree", 0),
    ("vtkFiltersImaging", 79),
    ("vtkFiltersModeling", 51),
    ("vtkFiltersParallel", 75),
    ("vtkFiltersParallelDIY2", 38),
    ("vtkFiltersParallelFlowPaths", 0),
    ("vtkFiltersParallelGeometry", 0),
    ("vtkFiltersParallelImaging", 0),
    ("vtkFiltersParallelMPI", 0),
    ("vtkFiltersParallelStatistics", 0),
    ("vtkFiltersParallelVerdict", 0),
    ("vtkFiltersPoints", 106),
    ("vtkFiltersProgrammable", 0),
    ("vtkFiltersPython", 0),
    ("vtkFiltersReduction", 8),
    ("vtkFiltersReebGraph", 0),
    ("vtkFiltersSMP", 0),
    ("vtkFiltersSelection", 0),
    ("vtkFiltersSources", 176),
    ("vtkFiltersStatistics", 186),
    ("vtkFiltersTemporal", 0),
    ("vtkFiltersTensor", 0),
    ("vtkFiltersTexture", 16),
    ("vtkFiltersTopology", 0),
    ("vtkFiltersVerdict", 31),
    ("vtkGeovisCore", 0),
    ("vtkGeovisGDAL", 0),
    ("vtkIOADIOS2", 0),
    ("vtkIOAMR", 45),
    ("vtkIOAlembic", 0),
    ("vtkIOAsynchronous", 0),
    ("vtkIOCGNSReader", 0),
    ("vtkIOCONVERGECFD", 0),
    ("vtkIOCellGrid", 0),
    ("vtkIOCesium3DTiles", 0),
    ("vtkIOChemistry", 10),
    ("vtkIOCityGML", 0),
    ("vtkIOCore", 54),
    ("vtkIOERF", 0),
    ("vtkIOEnSight", 70),
    ("vtkIOEngys", 0),
    ("vtkIOExodus", 299),
    ("vtkIOExport", 42),
    ("vtkIOExportGL2PS", 78),
    ("vtkIOExportPDF", 0),
    ("vtkIOFDS", 0),
    ("vtkIOFFMPEG", 0),
    ("vtkIOFLUENTCFF", 0),
    ("vtkIOFides", 0),
    ("vtkIOGDAL", 0),
    ("vtkIOGeoJSON", 0),
    ("vtkIOGeometry", 138),
    ("vtkIOH5Rage", 0),
    ("vtkIOH5part", 0),
    ("vtkIOHDF", 0),
    ("vtkIOIOSS", 143),
    ("vtkIOImage", 172),
    ("vtkIOImport", 23),
    ("vtkIOInfovis", 71),
    ("vtkIOLAS", 0),
    ("vtkIOLSDyna", 126),
    ("vtkIOLegacy", 197),
    ("vtkIOMINC", 0),
    ("vtkIOMPIImage", 0),
    ("vtkIOMPIParallel", 0),
    ("vtkIOMotionFX", 0),
    ("vtkIOMovie", 9),
    ("vtkIOMySQL", 0),
    ("vtkIONetCDF", 58),
    ("vtkIOOCCT", 0),
    ("vtkIOODBC", 0),
    ("vtkIOOMF", 0),
    ("vtkIOOggTheora", 0),
    ("vtkIOOpenVDB", 0),
    ("vtkIOPDAL", 0),
    ("vtkIOPIO", 0),
    ("vtkIOPLY", 0),
    ("vtkIOParallel", 71),
    ("vtkIOParallelExodus", 0),
    ("vtkIOParallelLSDyna", 0),
    ("vtkIOParallelNetCDF", 0),
    ("vtkIOParallelXML", 40),
    ("vtkIOParallelXdmf3", 0),
    ("vtkIOPostgreSQL", 0),
    ("vtkIOSQL", 83),
    ("vtkIOSegY", 0),
    ("vtkIOTRUCHAS", 0),
    ("vtkIOTecplotTable", 0),
    ("vtkIOVPIC", 0),
    ("vtkIOVeraOut", 0),
    ("vtkIOVideo", 65),
    ("vtkIOXML", 209),
    ("vtkIOXMLParser", 20),
    ("vtkIOXdmf2", 0),
    ("vtkIOXdmf3", 15),
    ("vtkImagingColor", 0),
    ("vtkImagingCore", 291),
    ("vtkImagingFourier", 4),
    ("vtkImagingGeneral", 20),
    ("vtkImagingHybrid", 0),
    ("vtkImagingMath", 0),
    ("vtkImagingMorphological", 0),
    ("vtkImagingOpenGL2", 0),
    ("vtkImagingSources", 0),
    ("vtkImagingStatistics", 40),
    ("vtkImagingStencil", 0),
    ("vtkInfovisBoostGraphAlgorithms", 0),
    ("vtkInfovisCore", 0),
    ("vtkInfovisLayout", 32),
    ("vtkInteractionImage", 46),
    ("vtkInteractionStyle", 93),
    ("vtkInteractionWidgets", 918),
    ("vtkParallelCore", 476),
    ("vtkParallelMPI", 0),
    ("vtkParallelMPI4Py", 0),
    ("vtkPythonContext2D", 0),
    ("vtkRenderingAnari", 23),
    ("vtkRenderingAnnotation", 0),
    ("vtkRenderingCellGrid", 0),
    ("vtkRenderingContext2D", 163),
    ("vtkRenderingContextOpenGL2", 0),
    ("vtkRenderingCore", 2941),
    ("vtkRenderingExternal", 0),
    ("vtkRenderingFFMPEGOpenGL2", 0),
    ("vtkRenderingFreeType", 13),
    ("vtkRenderingGL2PSOpenGL2", 0),
    ("vtkRenderingHyperTreeGrid", 19),
    ("vtkRenderingImage", 0),
    ("vtkRenderingLICOpenGL2", 195),
    ("vtkRenderingLOD", 0),
    ("vtkRenderingLabel", 90),
    ("vtkRenderingMatplotlib", 0),
    ("vtkRenderingOpenGL2", 359),
    ("vtkRenderingOpenVR", 30),
    ("vtkRenderingOpenXR", 0),
    ("vtkRenderingParallel", 153),
    ("vtkRenderingParallelLIC", 0),
    ("vtkRenderingQt", 0),
    ("vtkRenderingRayTracing", 11),
    ("vtkRenderingSceneGraph", 73),
    ("vtkRenderingUI", 0),
    ("vtkRenderingVR", 166),
    ("vtkRenderingVRModels", 0),
    ("vtkRenderingVolume", 262),
    ("vtkRenderingVolumeAMR", 0),
    ("vtkRenderingVolumeOpenGL2", 0),
    ("vtkRenderingVtkJS", 0),
    ("vtkTestingRendering", 0),
    ("vtkViewsContext2D", 0),
    ("vtkViewsCore", 68),
    ("vtkViewsInfovis", 414),
    ("vtkWebCore", 0),
    ("vtkWebGLExporter", 28),
]

counts = np.array([d[1] for d in data])
names = np.array([d[0] for d in data])

filt = counts != 0
inds = np.argsort(counts[filt])

counts = counts[filt][inds]
names = names[filt][inds]

fig, ax = plt.subplots(figsize=(12, 6))

ax.bar(names, counts)
ax.tick_params(axis="x", rotation=90)
ax.set_yscale("log")
ax.set_ylabel("Methods per Module")
fig.tight_layout()
fig.savefig("vtk-methods-per-module.png")
