on: [push, pull_request]

name: Test-Suite stable ubuntu-24.04

jobs:
  CI-stable-ubuntu-24_04:
    uses: ./.github/workflows/reuse.yml
    with:
      toolchain: stable
      os: ubuntu-24.04
      packages: libvtk9.1 libvtk9-dev
      environment_vars: 
