on: [push, pull_request]

name: Test-Suite beta ubuntu-22.04

jobs:
  CI-beta-ubuntu-22_04:
    uses: ./.github/workflows/reuse.yml
    with:
      toolchain: beta
      os: ubuntu-22.04
      packages: libvtk9.1 libvtk9.1-dev
      features: --features vtk9-1
