on: [push, pull_request]

name: Test-Suite nightly ubuntu-latest

jobs:
  CI-nightly-ubuntu-latest:
    uses: ./.github/workflows/reuse.yml
    with:
      toolchain: nightly
      os: ubuntu-latest
      features: --features vtk9-1
