on: [push, pull_request]

name: Test-Suite stable ubuntu-22.04

jobs:
  CI-stable-ubuntu-22_04:
    uses: ./.github/workflows/reuse.yml
    with:
      toolchain: stable
      os: ubuntu-22.04
      packages: libvtk9.1 libvtk9-dev
      environment_vars: VTK_VERSION=9-1
